### ISSUE TITLE
Försenad student

### ISSUE THREAD

**Issue by waseemassaf** [dbwebb-se/webtec#25]
Hej, jag hoppade in till programmet Software en vecka sen, jag missade första inlämningen. Vet någon vilka sidor man ska läsa i boken för att bli förberedd för att göra uppfiten?

**Comment by mosbth** [comment]
Programmet Software Engineering läser inte denna kursen.

Den sön 10 sep. 2023 kl 19:25 skrev waseemassaf ***@***.***>:

**Comment by waseemassaf** [comment]
Jag vet inte hur man använder Github än.. så vad är det för kurs här? Hur hittar jag kursen Python Mikael? ber om ursäkt för missförstånd

**Comment by mosbth** [comment]
Gå till Canvas. Där bör du se de kurser du deltar i. Tex python-kursen.
Om oklart, gå till studentreceptionen och be om hjälp imorgon att hitta dina kurser på Canvas.

**Comment by waseemassaf** [comment]
Tusentack Mikael!
